# Generated by Django 4.2.4 on 2023-08-31 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('get_an_invitation', models.BooleanField(default=False)),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application_item',
                'verbose_name_plural': 'application_items',
                'db_table': 'application_item',
            },
        ),
    ]
