# Generated by Django 4.2.4 on 2023-09-01 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0002_rename_application_applicationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationitem',
            name='applied_on',
            field=models.DateField(default=datetime.date(2023, 9, 1)),
        ),
    ]
